version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "academydb"
      POSTGRES_USER: "user1"
      POSTGRES_PASSWORD: "pgpwd1"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: